# Generated by Django 5.0.9 on 2026-06-09 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artikel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artikelnummer', models.CharField(max_length=50, unique=True, verbose_name='Artikelnummer')),
                ('bezeichnung', models.CharField(max_length=200, verbose_name='Bezeichnung')),
                ('beschreibung', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('preis', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preis (€)')),
                ('bestand', models.PositiveIntegerField(default=0, verbose_name='Bestand')),
            ],
            options={
                'verbose_name': 'Artikel',
                'verbose_name_plural': 'Artikel',
                'ordering': ['artikelnummer'],
            },
        ),
        migrations.CreateModel(
            name='Auftrag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auftragsdatum', models.DateField(auto_now_add=True, verbose_name='Auftragsdatum')),
                ('status', models.CharField(choices=[('offen', 'Offen'), ('bearbeitung', 'In Bearbeitung'), ('abgeschlossen', 'Abgeschlossen'), ('storniert', 'Storniert')], default='offen', max_length=20, verbose_name='Status')),
                ('notizen', models.TextField(blank=True, verbose_name='Notizen')),
            ],
            options={
                'verbose_name': 'Auftrag',
                'verbose_name_plural': 'Aufträge',
                'ordering': ['-auftragsdatum'],
            },
        ),
        migrations.CreateModel(
            name='Kunde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-Mail')),
                ('telefon', models.CharField(blank=True, max_length=50, verbose_name='Telefon')),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
            ],
            options={
                'verbose_name': 'Kunde',
                'verbose_name_plural': 'Kunden',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Auftragsposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menge', models.PositiveIntegerField(default=1, verbose_name='Menge')),
                ('einzelpreis', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Einzelpreis (€)')),
                ('artikel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='positionen', to='crm.artikel', verbose_name='Artikel')),
                ('auftrag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positionen', to='crm.auftrag', verbose_name='Auftrag')),
            ],
            options={
                'verbose_name': 'Auftragsposition',
                'verbose_name_plural': 'Auftragspositionen',
            },
        ),
        migrations.AddField(
            model_name='auftrag',
            name='kunde',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auftraege', to='crm.kunde', verbose_name='Kunde'),
        ),
    ]
